site_name: 'Documentações diversas'

nav:
  - Home: index.md
  - Aplicações:
    - Keycloak: aplicacoes/keycloak.md
    - Gluu: aplicacoes/gluu.md
    - Jitsi: aplicacoes/jitsi.md
    - Mattermost: aplicacoes/mattermost.md
  - Kubernetes:
    -  Monitoramento:
        - Prometheus: monitoramento/prometheus/prometheus.md

plugins:
  - techdocs-core

theme:
  name: material
  language: pt

markdown_extensions:
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences