site_name: 'Documentações diversas'

nav:
  - Home: index.md
  - Aplicações:
    - Keycloak: keycloak.md
    - Gluu: gluu.md
    - Jitsi: jitsi.md
  - Kubernetes:
    -  Monitoramento:
        - Prometheus: prometheus/prometheus.md

plugins:
  - techdocs-core

theme:
  name: material
  language: pt

markdown_extensions:
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences